import 'animal.dart';

class Pig extends Animal {
  String status;
  String furColor;
  String earShape;

  Pig(
    String serialNumber,
    String name,
    String register,
    String breed,
    String blood,
    String origin,
    String sex,
    double weight,
    String birthDate,
    double originalPrice,
    double marketPrice,
    int age,
    String dietType,
    List<DateTime> feedingTimes,
    List<DateTime> veterinaryVisits,
    double width,
    double length,
    bool breedPurityCertificate,
    bool cio,
    double custo,
    List<String> vaccinations,
    List<DateTime> vaccinationDates,
    List<String> medicalTreatments,
    this.status,
    this.furColor,
    this.earShape,
  ) : super(
          serialNumber: serialNumber,
          name: name,
          register: register,
          breed: breed,
          blood: blood,
          origin: origin,
          sex: sex,
          weight: weight,
          birthDate: birthDate,
          originalPrice: originalPrice,
          marketPrice: marketPrice,
          age: 0,
          dietType: "",
          feedingTimes: [],
          veterinaryVisits: [],
          width: 0.0,
          length: 0.0,
          breedPurityCertificate: false,
          cio: false,
          custo: 0.0,
          vaccinations: [],
          vaccinationDates: [],
          medicalTreatments: [],
        );

  Pig.initialize()
      : status = "Healthy",
        furColor = "",
        earShape = "",
        super(
          serialNumber: "12345",
          name: "Bessie",
          register: "R123",
          breed: "Holstein",
          blood: "A",
          origin: "USA",
          sex: "Female",
          weight: 500.0,
          birthDate: "01/03/2020",
          originalPrice: 1000.0,
          marketPrice: 800.0,
          age: 0,
          dietType: "",
          feedingTimes: [],
          veterinaryVisits: [],
          width: 0.0,
          length: 0.0,
          breedPurityCertificate: false,
          cio: false,
          custo: 0.0,
          vaccinations: [],
          vaccinationDates: [],
          medicalTreatments: [],
        );
}
